### PR TITLE
Small language fixes

### PR DESCRIPTION
**Pull request by trickvi**
Not really huge contributions but a typo fix and "improved" language.

### CODE REVIEW

**Comment by fin** [comment]
thanks a lot!

**Comment by trickvi** [comment]
@fin I really want to help out, is there anything you want to include but wouldn't want to do yourself?

**Comment by fin** [comment]
thanks for the offer!

replacing the bootstrap carousel (for uploaded images) with something that shows multiple images at once (but maybe scrolls between them) would be great.

@michaelem may be working on that already though. (m, could you weigh in?)

different idea: i haven't really looked at the print stylesheets yet, it would be great if the submission list were printable.

**Comment by michaelem** [comment]
I'd try to integrate an image grid that I use at work tonight if you like how it looks (example: http://www.lomography.com/homes/michaelem/albums/2074506-foma-retropan-320).

**Pull request merged**
